### ISSUE TITLE
Erreur 400 sur la récupération des images

### ISSUE THREAD

**Issue by sholine** [izneo-get/mangas-get#1]
J'ai constaté une erreur 400 lors de la phase de récupération des images :
`Erreur : Aucune page trouvée`
`Erreur : 400`
Après avoir rejoué la requête en question avec un postman (dans get_pages), l'erreur retournée par Mangas.io est :
`Cannot query field "blurhash" on type "ImageMeta".`

Enfin, en retirant le paramètre "blurhash" dans la query qui est faite, cela fonctionne de nouveau (mais je ne sais pas quelle était son utilité)

**Comment by izneo-get** [comment]
Est-ce que ça le fait pour tous les mangas ?
Si ce n'est pas le cas, pouvez-vous donner un exemple ?

**Comment by sholine** [comment]
Je l'ai constaté au moins avec ces 2 mangas :
https://www.mangas.io/lire/tu-nas-pas-change-umino-senpai
et
https://www.mangas.io/lire/berserk-of-gluttony

**Comment by izneo-get** [comment]
La version [2d005e3](https://github.com/izneo-get/mangas-get/commit/2d005e379f3a78f7c87f959dcc3a73c868aab3ee) devrait résoudre le problème.
Tiens moi informé.

**Comment by sholine** [comment]
Je viens de tester mais j'ai l'erreur :
`ModuleNotFoundError: No module named 'Scrapers.piccoma_com_scraper'`
J'ai tenté de le corriger en rajoutant cette dépendance dans requirements.txt
`pyccoma==0.7.2`
Mais je me retrouve avec un conflit de dépendances :
`The conflict is caused by:`
`    The user requested requests==2.32.3`
`    pyccoma 0.7.2 depends on requests==2.26.0`

**Comment by izneo-get** [comment]
Oups !
Pyccoma n'est pas une librairie sur PyPi, mais une librairie que j'avais en cours de développement. 
J'ai commité un peu trop vite. 
[62f3bac](https://github.com/izneo-get/mangas-get/commit/62f3bac4f53b11cc0c47f3796dc4b28d82d6ff73) devrait être bon.

**Comment by sholine** [comment]
C'est bon tout marche nickel ! 👍 Merci pour ta réactivité !
